name: Inthedepths
version: '${project.version}'
main: us.glasscrab.i.inthedepths.Inthedepths
api-version: 1.19
authors: [ glasscrab ]
description: Special items rarely spawning in certain locations of the world.
website: i.glasscrab.us
commands:
  giveopal:
    description: Gives a crystal to the player.
    usage: /giveopal <player>
    permission: inthedepths.giveopal
    default: op
permissions:
    inthedepths.giveopal:
        description: Gives a Charged Opal to the player.
        default: op